language: node_js
node_js:
- '8'
cache: yarn
script:
- npm run dist
deploy:
  provider: firebase
  token:
    secure: "pxJ2PA5e78ZRyLBoFJ21aferpbCgk/iPmm5FdOluT2MCtjkjLJMTht2fINk9wZks6oVPVMrDwAYNwtXKyznJju48o7xIiqyjAvsx9GGrVVTU1zaVTD81wlY4LRSMpu3QHtcdiCfWo9WDWaAmLD+0JfrD1LGcJdSe8KIMwqHDZMzadmhKhHdfoY4PV8CgXkiB9ZYWprC9oXggNx3cRMNittkjIfTA3MtxlxEzNDIw9UeOaIaL0MSD4Fb4IPchQby4CBPc577pvKvLoapkrqYLKGvbpCL5Qavgw+V8y3BNmGzdwMiXTd4btU8jTnq9xmNHHRMsNQGcU98Nv5lDfPmRJ+UW/m0ybVvphnlR0IVLTG5BEIKRiNKnZlWfdsHTc3nUP4g63dEMa8QFJJev4YAkHTNCXVc3g++d5qSX2sbUldPTiBHaeGf0H0jnLTqwOPUI9cWT0DCoWJlNsZ1Elhd9i7jAp+mTeNJas/q8SqrtbTyL8YPmDOD+/ms9BMpw3R4mVNYrGqtzkzeMPLMlFwlcw3ztT5dckxV49YLbcwXtF0Ui4qEoI97upFDbzGHBvE9unGQb8kvX0nEwWvwK+9E7KsYZn/OLDxzMHHlgq37XA9cm3/HuCY0fQ8fc5IDcoET3+mcTmmhkl+/72PFgwi3XWP05Fkk+s1p8yMsRXj7tHtQ="
  message: "deployed by travis"
