packageExtensions:
  '@google-cloud/pubsub@*':
    dependencies:
      '@grpc/grpc-js': '*'
  '@firebase/firestore@*':
    dependencies:
      protobufjs: '*'
  '@firebase/testing@*':
    dependencies:
      '@firebase/component': '*'
      '@grpc/proto-loader': '*'
