import { writeFileSync } from 'fs';
import * as git from 'git-rev-sync';
const { version } = require('./package.json');

const data = {
  version,
  revision: git.short(),
  timestamp: new Date().toISOString(),
};

console.log(data);

const content = `// this file is automatically generated by git.version.ts\nexport const version = ${JSON.stringify(data)};`;

writeFileSync('src/environments/version.ts', content, 'utf8');
