import { writeFileSync } from 'fs';
import * as git from 'git-rev-sync';
const { version } = require('./package.json');

const revision = git.short();

console.log(`version: '${version}', revision: '${revision}'`);

const content = '// this file is automatically generated by git.version.ts\n' +
  `export const version = { version: '${version}', revision: '${revision}' };`;

writeFileSync('src/environments/version.ts', content, 'utf8');
